/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View;

import com.DataBase.SingletonConnection;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ucef
 */
public class addAdmin extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement ps;
    ResultSet rs;
    /**
     * Creates new form addAdmin
     */
    public addAdmin() {
        initComponents();
        
        
        
        
        
        
        /*conn=SingletonConnection.getConnection();
        try {
            ps=conn.prepareStatement("SELECT users.id_user FROM users WHERE users.role=? ");
            ps.setString(1, "admin");
            rs=ps.executeQuery();
            while(rs.next())
            {
                userItem.addItem(item);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(addAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }
    
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        System.out.println("ee");
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_img_user.getWidth(), lbl_img_user.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
      
          ActionListener a=  new ActionListener() {

        public void actionPerformed(ActionEvent e) {
        
            JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.home")));
          //filter the files
            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              String path = selectedFile.getAbsolutePath();
              
              lbl_img_user.setIcon(ResizeImage(path));
              //path_txt.setText(path);
          }
           //if the user click on save in Jfilechooser


          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
        }
          }
      ;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mailTxt = new javax.swing.JTextField();
        pwdtxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        RoleItem = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbl_img_user = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addUser = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("PsudoName     :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(31, 135, 125, 29);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("Email                  :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(33, 81, 125, 29);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel4.setText("Password         :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(31, 182, 125, 29);
        jPanel1.add(mailTxt);
        mailTxt.setBounds(170, 80, 183, 27);
        jPanel1.add(pwdtxt);
        pwdtxt.setBounds(168, 183, 183, 27);
        jPanel1.add(nametxt);
        nametxt.setBounds(168, 136, 183, 27);

        RoleItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "client", "admin" }));
        jPanel1.add(RoleItem);
        RoleItem.setBounds(170, 230, 180, 27);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setText("Image                      :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 230, 125, 29);

        lbl_img_user.setText("             PHOTO");
        lbl_img_user.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_img_user);
        lbl_img_user.setBounds(540, 70, 140, 150);

        browse.setText("Upload");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        jPanel1.add(browse);
        browse.setBounds(570, 230, 90, 29);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setText("Role                     :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(31, 229, 125, 29);

        addUser.setText("Save");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        jPanel1.add(addUser);
        addUser.setBounds(470, 320, 90, 29);

        jButton2.setText("Annuler");
        jPanel1.add(jButton2);
        jButton2.setBounds(590, 320, 80, 29);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        browse.addActionListener(a);
    }//GEN-LAST:event_browseActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
       conn=SingletonConnection.getConnection();
       String email=mailTxt.getText();
       boolean ext=false;
       String pwd=pwdtxt.getText();
       String role=RoleItem.getSelectedItem().toString();
       String nom=nametxt.getText();
       String sql="insert into users(email,role,created,modified) values(?,?,CURRENT_DATE(),CURRENT_DATE())";
        try {
            PreparedStatement s2=conn.prepareStatement("select * from users where email=?");
            s2.setString(1, email);
            s2.executeQuery();
            ResultSet r=s2.getResultSet();
            if(r.next())
            {
                ext=true;
            JOptionPane.showMessageDialog(null, " user deja exist");    
            }else
            {
            PreparedStatement pss=conn.prepareStatement(sql);
            pss.setString(1, email);
            pss.setString(2, pwd);
            pss.setString(3, role);
            pss.executeUpdate();
            System.out.println("users inscrit");  
            }
          
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RoleItem;
    private javax.swing.JButton addUser;
    private javax.swing.JButton browse;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_img_user;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField pwdtxt;
    // End of variables declaration//GEN-END:variables
}
