/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View;

import com.DataBase.SingletonConnection;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YouSsef
 */
public class Client extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement ps,ps2;
    ResultSet rs,rs2;
    DefaultTableModel model=new DefaultTableModel();
    String path="src/icon/";//////// pour windows src\\icon\\
    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        this.setSize(1090, 655);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        conn=SingletonConnection.getConnection();
        try {
            ps=conn.prepareStatement("Select * from villes ");
            ps.executeQuery();
            rs=ps.getResultSet();
            while(rs.next()){
                        villeItem.addItem(rs.getString("name"));
                             }
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        /*
        Remplir le tableau
        */
        model.addColumn("NOM");
        model.addColumn("EMAIL");
        model.addColumn("PASSWORD");
        model.addColumn("TEL");
        model.addColumn("FAX");
        model.addColumn("ADRESSE");
        model.addColumn("VILLE");
        model.addColumn("PAYS");
        
        
        try{
            Statement st2 = conn.createStatement();
            rs2=st2.executeQuery("select * from clients c, villes v ,users u where c.ville_id=v.id_ville and c.user_id=u.id_user");
            while(rs2.next())
            {
                model.addRow(new Object[] {
                    rs2.getString("nom"),
                    rs2.getString("email"),
                    rs2.getString("password"),
                    rs2.getString("tel"),
                    rs2.getString("fax"),
                    rs2.getString("adresse"),
                    rs2.getString("name"),
                    rs2.getString("pays")
                });
            }
        }catch(Exception e)
        {
            System.err.println(e);
        }
        tble.setModel(model);
        
        /*
        Fin remplissage
        */
                ImageIcon ic=new ImageIcon(path+"add.png");
                Image ii=ic.getImage();
                Image ii2=ii.getScaledInstance(btville.getWidth(), btville.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icc=new ImageIcon(ii2);
         
                    btville.setIcon(icc);
                    
                ImageIcon ab=new ImageIcon(path+"searchUser.png");
                Image bc=ab.getImage();
                Image cd=bc.getScaledInstance(serchUser.getWidth(), serchUser.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon de=new ImageIcon(cd);
                serchUser.setIcon(de);
                
                ImageIcon a1=new ImageIcon(path+"addCl.png");
                Image a2=a1.getImage();
                Image a3=a2.getScaledInstance(addcl.getWidth(), addcl.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon a4=new ImageIcon(a3);
                addcl.setIcon(a4);
                
                ImageIcon b1=new ImageIcon(path+"update.png");
                Image b2=b1.getImage();
                Image b3=b2.getScaledInstance(updatebt.getWidth(), updatebt.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon b4=new ImageIcon(b3);
                updatebt.setIcon(b4);
                
                ImageIcon d1=new ImageIcon(path+"deletecl.png");
                Image d2=d1.getImage();
                Image d3=d2.getScaledInstance(deletebt.getWidth(), deletebt.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon d4=new ImageIcon(d3);
                deletebt.setIcon(d4);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void afficher()
    {
        
            try{
                
            model.setRowCount(0);
            Statement st2 = conn.createStatement();
            rs2=st2.executeQuery("select * from clients c, villes v ,users u where c.ville_id=v.id_ville and c.user_id=u.id_user");
            while(rs2.next())
            {
                model.addRow(new Object[] {
                    rs2.getString("nom"),
                    rs2.getString("email"),
                    rs2.getString("password"),
                    rs2.getString("tel"),
                    rs2.getString("fax"),
                    rs2.getString("adresse"),
                    rs2.getString("name"),
                    rs2.getString("pays")
                });
            }
        }catch(Exception e)
        {
            System.err.println(e);
        }
        tble.setModel(model);
    }
    private void deplace(int i)
    {
        try{
            mailtxt.setText(model.getValueAt(i,1).toString());
            pwdtxt.setText(model.getValueAt(i,2).toString());
            nomtxt.setText(model.getValueAt(i,0).toString());
            teltxt.setText(model.getValueAt(i,3).toString());
            faxtxt.setText(model.getValueAt(i,4).toString());
            adrtxt.setText(model.getValueAt(i,5).toString());
            villeItem.setSelectedItem(model.getValueAt(i,6).toString());
            paystxt.setText(model.getValueAt(i,7).toString());
        }catch(Exception e)
        {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());
        }
    }
    /*
    
    
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        paystxt = new javax.swing.JTextField();
        mailtxt = new javax.swing.JTextField();
        pwdtxt = new javax.swing.JTextField();
        nomtxt = new javax.swing.JTextField();
        teltxt = new javax.swing.JTextField();
        faxtxt = new javax.swing.JTextField();
        adrtxt = new javax.swing.JTextField();
        villeItem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        serchUser = new javax.swing.JButton();
        addcl = new javax.swing.JButton();
        updatebt = new javax.swing.JButton();
        deletebt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        btville = new javax.swing.JButton();
        txtre = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 233));
        jPanel1.setLayout(null);

        jLabel2.setText("Pays                 :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 430, 100, 30);

        jLabel3.setText("Fax                   :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 280, 100, 30);

        jLabel4.setText("Tel                     :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 240, 100, 30);

        jLabel5.setText("Email                   :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 90, 100, 30);

        jLabel7.setText("Password            :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 140, 100, 30);

        jLabel6.setText("Nom & Prénom   :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 190, 100, 30);

        jLabel8.setText("Adresse            :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 330, 100, 30);

        jLabel9.setText("Ville                   :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 380, 100, 30);

        paystxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paystxtActionPerformed(evt);
            }
        });
        jPanel1.add(paystxt);
        paystxt.setBounds(120, 430, 210, 30);
        jPanel1.add(mailtxt);
        mailtxt.setBounds(120, 90, 210, 30);

        pwdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdtxtActionPerformed(evt);
            }
        });
        jPanel1.add(pwdtxt);
        pwdtxt.setBounds(120, 140, 210, 30);

        nomtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomtxtActionPerformed(evt);
            }
        });
        jPanel1.add(nomtxt);
        nomtxt.setBounds(120, 190, 210, 30);

        teltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teltxtActionPerformed(evt);
            }
        });
        jPanel1.add(teltxt);
        teltxt.setBounds(120, 240, 210, 30);

        faxtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxtxtActionPerformed(evt);
            }
        });
        jPanel1.add(faxtxt);
        faxtxt.setBounds(120, 280, 210, 30);

        adrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adrtxtActionPerformed(evt);
            }
        });
        jPanel1.add(adrtxt);
        adrtxt.setBounds(120, 330, 210, 30);

        villeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villeItemActionPerformed(evt);
            }
        });
        jPanel1.add(villeItem);
        villeItem.setBounds(120, 380, 200, 30);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information Du Client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 390, 430);

        serchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchUserActionPerformed(evt);
            }
        });
        jPanel1.add(serchUser);
        serchUser.setBounds(980, 540, 50, 40);

        addcl.setText("Ajouter");
        addcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclActionPerformed(evt);
            }
        });
        jPanel1.add(addcl);
        addcl.setBounds(50, 490, 70, 50);

        updatebt.setText("Modifier");
        updatebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtActionPerformed(evt);
            }
        });
        jPanel1.add(updatebt);
        updatebt.setBounds(150, 490, 70, 50);

        deletebt.setText("Supprimer");
        deletebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtActionPerformed(evt);
            }
        });
        jPanel1.add(deletebt);
        deletebt.setBounds(250, 490, 70, 50);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 70, 630, 402);

        btville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvilleActionPerformed(evt);
            }
        });
        jPanel1.add(btville);
        btville.setBounds(330, 380, 50, 30);

        txtre.setText("jTextField1");
        jPanel1.add(txtre);
        txtre.setBounds(760, 550, 210, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(760, 510, 130, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel10.setText("Rechercher par:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(660, 520, 90, 20);

        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rechercher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(540, 490, 520, 100);

        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listes Des Clients", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(420, 50, 650, 440);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1080, 620);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paystxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paystxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paystxtActionPerformed

    private void pwdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdtxtActionPerformed

    private void nomtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomtxtActionPerformed

    private void teltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teltxtActionPerformed

    private void faxtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faxtxtActionPerformed

    private void adrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adrtxtActionPerformed

    private void serchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchUserActionPerformed
       try
       {
           model.setRowCount(0);//pour vider la listes des Clients
           PreparedStatement v=conn.prepareStatement("select * from clients c, villes v ,users u where c.ville_id=v.id_ville and c.user_id=u.id_user and c.nom like '%?%'");
           v.setString(1, txtre.getText());
           v.executeQuery();
            ResultSet rr=v.getResultSet();
           while(rr.next())
           {
               Object [] cl={rs2.getString("nom"),
                    rr.getString("email"),
                    rr.getString("password"),
                    rr.getString("tel"),
                    rr.getString("fax"),
                    rr.getString("adresse"),
                    rr.getString("name"),
                    rr.getString("pays")};
               model.addRow(cl);
           }
           if(model.getRowCount()==0)
               JOptionPane.showMessageDialog(null, "makyn hta chi wahed bhad smiya");
           else {
             int  i=0;
             deplace(i);
           }
       }catch(Exception e)
       {
           System.out.println("loooooooooooooo");
           JOptionPane.showMessageDialog(null, e.getMessage());
       }
                                            
    }//GEN-LAST:event_serchUserActionPerformed

    private void villeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villeItemActionPerformed
      
    }//GEN-LAST:event_villeItemActionPerformed

    private void addclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclActionPerformed
    //insert into users() values(mail,passwd,client,CURRENT_DATE(),CURRENT_DATE());
    boolean ext=false;
    String mail=mailtxt.getText();
    String pwd=pwdtxt.getText();
    String sql="insert into users(email,password,created,modified) values (?,?,CURRENT_DATE(),CURRENT_DATE())";
        try {
            PreparedStatement s2=conn.prepareStatement("select * from users where email=?");
            s2.setString(1, mail);
            s2.executeQuery();
            ResultSet r=s2.getResultSet();
            if(r.next())
            {
                ext=true;
            JOptionPane.showMessageDialog(null, " user deja exist");    
            }else
            {
            PreparedStatement pss=conn.prepareStatement(sql);
            pss.setString(1, mail);
            pss.setString(2, pwd);
            pss.executeUpdate();
            System.out.println("users inscrit");  
            }
          
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
      //insert into clients(nom,tel,ville_id,user_id,fax,adresse,pays)
     String nom=nomtxt.getText();
     int tel=Integer.parseInt(teltxt.getText());
     int fax=Integer.parseInt(faxtxt.getText()); 
     String adr=adrtxt.getText();
     String pays=paystxt.getText();
     String vill=villeItem.getSelectedItem().toString();
     //mail
     int id_usr = 0;
     if(ext==false){
        try {
            PreparedStatement s1=conn.prepareStatement("select * from users where email=?");
            s1.setString(1, mail);
            s1.executeQuery();
            ResultSet r=s1.getResultSet();
            r.next();
             id_usr=r.getInt("id_user");
            r.close();
            s1.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
     
     //ville
        int id_ville=1;
        try {
            PreparedStatement ww=conn.prepareStatement("select * from villes where name=?");
            ww.setString(1, vill);
            ww.executeQuery();
            ResultSet rt=ww.getResultSet();
            rt.next();
            id_ville= rt.getInt("id_ville");
           rt.close();
           ww.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        //nom,tel,fax,adr,pays,id_usr,id_ville
       String sql2="insert into clients(nom,tel,ville_id,user_id,fax,adresse,pays)"
               + "values (?,?,?,?,?,?,?)";
       if(id_usr!=0){
        try {
            PreparedStatement pp=conn.prepareStatement(sql2);
            pp.setString(1, nom);
            pp.setInt(2, tel);
            pp.setInt(3, id_ville);
            pp.setInt(4, id_usr);
            pp.setInt(5, fax);
            pp.setString(6, adr);
            pp.setString(7, pays);
            pp.executeUpdate();
            System.out.println("client bien ajoutee");
            JOptionPane.showMessageDialog(null, " Client Bien ajouté ");
            afficher();
            mailtxt.setText("");pwdtxt.setText("");nomtxt.setText("");
             paystxt.setText("");teltxt.setText("");faxtxt.setText("");adrtxt.setText("");villeItem.setSelectedItem(3);
            
        } catch (SQLException ee) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ee);
        }
       
       }
     }
    }//GEN-LAST:event_addclActionPerformed

    private void updatebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtActionPerformed
       
        String mail=mailtxt.getText();
        String pwd=pwdtxt.getText();
        String nom=nomtxt.getText();
        int tel=Integer.parseInt(teltxt.getText());
        int fax=Integer.parseInt(faxtxt.getText()); 
        String adr=adrtxt.getText();
        String pays=paystxt.getText();
        String vill=villeItem.getSelectedItem().toString();
        
        int id_usr = 0;
        try {
            PreparedStatement s1=conn.prepareStatement("select * from users where email=?");
            s1.setString(1, mail);
            s1.executeQuery();
            ResultSet r=s1.getResultSet();
            r.next();
             id_usr=r.getInt("id_user");
            r.close();
            s1.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* if(JOptionPane.showConfirmDialog(null, "wach bessa7","modification",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            try {
                PreparedStatement po=conn.prepareStatement("");
                st.executeUpdate("Update etudiant set Nom='"+txtno.getText()+"',prenom='"+txtpr.getText()+"',branche='"+txtbr.getSelectedItem().toString()+"',note='"+txtnot.getText()+
                        "' where id="+txtid.getText());
                afficher();
                 JOptionPane.showMessageDialog(null, "bien modifier");
                 
            } catch (SQLException ex) {
                Logger.getLogger(Gestion_des_notes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
    }//GEN-LAST:event_updatebtActionPerformed

    private void deletebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtActionPerformed
       
        
        String mail=mailtxt.getText();
        String nom=nomtxt.getText();
        if(JOptionPane.showConfirmDialog(null, "wach bessa7 baghi tmsa7 "+nom,"modification",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {int id_usr = 0;
        try {
            PreparedStatement s1=conn.prepareStatement("select * from users where email=?");
            s1.setString(1, mail);
            s1.executeQuery();
            ResultSet r=s1.getResultSet();
            r.next();
             id_usr=r.getInt("id_user");
            r.close();
            s1.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            PreparedStatement oo=conn.prepareStatement("delete from clients where user_id=?");
            oo.setInt(1, id_usr);
            oo.executeUpdate();
            oo.close();
            PreparedStatement o=conn.prepareStatement("delete from users where id_user=?");
            o.setInt(1, id_usr);
            o.executeUpdate();
            o.close();
            afficher();
             mailtxt.setText("");pwdtxt.setText("");nomtxt.setText("");
             paystxt.setText("");teltxt.setText("");faxtxt.setText("");adrtxt.setText("");villeItem.setSelectedItem(3);
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_deletebtActionPerformed

    private void btvilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvilleActionPerformed
       addVille a=new addVille();
       a.setVisible(true);
      this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btvilleActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        try
        {
            int i=tble.getSelectedRow();
            deplace(i);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "erruer de delacement "+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tbleMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcl;
    private javax.swing.JTextField adrtxt;
    private javax.swing.JButton btville;
    private javax.swing.JButton deletebt;
    private javax.swing.JTextField faxtxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mailtxt;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JTextField paystxt;
    private javax.swing.JTextField pwdtxt;
    private javax.swing.JButton serchUser;
    private javax.swing.JTable tble;
    private javax.swing.JTextField teltxt;
    private javax.swing.JTextField txtre;
    private javax.swing.JButton updatebt;
    private javax.swing.JComboBox<String> villeItem;
    // End of variables declaration//GEN-END:variables
}
