/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View;

import com.DataBase.SingletonConnection;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author YouSsef
 */
public class Home extends javax.swing.JFrame {
PreparedStatement ps;
    Connection conn;
    ResultSet rs;
     String path="src/icon/";
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
         conn=SingletonConnection.getConnection();
        //710, 462
        this.setExtendedState(this.MAXIMIZED_BOTH);
        //this.setSize(863, 431);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
         currentDate();
        System.out.println(Login.getId());
        String sql ="select * from admins where id_admin=? ";

        try {
            ps=conn.prepareStatement(sql);
            ps.setInt(1,Login.getId());
           
           // pst.setBytes(7,person_image);
            rs=ps.executeQuery();
            if(rs.next()){
        byte[] img = rs.getBytes("Img");
        String nom_con=rs.getString("nom");
        conect_user.setText(nom_con);
            ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().
                    getScaledInstance(img_lbl.getWidth(), img_lbl.getHeight(),
                            Image.SCALE_SMOOTH));
            img_lbl.setIcon(imageIcon);}
            else
            {
                
                ImageIcon ic=new ImageIcon(path+"admin.png");
                Image ii=ic.getImage();
                Image ii2=ii.getScaledInstance(img_lbl.getWidth(), img_lbl.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icc=new ImageIcon(ii2);
                /*
                irst way: Image img = myIcon2.getImage(); Image newimg = img.getScaledInstance(230, 310, java.awt.Image.SCALE_SMOOTH);
 newIcon = new ImageIcon(newimg);
                */
                    img_lbl.setIcon(icc);
    }
        } catch (SQLException e) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, e);
        }
        
        
        
        ImageIcon a1=new ImageIcon(path+"clients.png");
                Image a2=a1.getImage();
                Image a3=a2.getScaledInstance(jButton4.getWidth(), jButton4.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon a4=new ImageIcon(a3);
                jButton4.setIcon(a4);
                
                ImageIcon b1=new ImageIcon(path+"voiture.png");
                Image b2=b1.getImage();
                Image b3=b2.getScaledInstance(gvoi.getWidth(), gvoi.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon b4=new ImageIcon(b3);
                gvoi.setIcon(b4);
                
                ImageIcon d1=new ImageIcon(path+"demande.jpg");
                Image d2=d1.getImage();
                Image d3=d2.getScaledInstance(gdem.getWidth(), gdem.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon d4=new ImageIcon(d3);
                gdem.setIcon(d4);
        
    }
    public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        txt_date.setText(day+" - "+(month+1)+" - "+year);
        
         int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        txt_time.setText(hour+":"+(minute)+":"+second);
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        img_lbl = new javax.swing.JLabel();
        gvoi = new javax.swing.JButton();
        gdem = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        conect_user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        txt_date = new javax.swing.JMenu();
        txt_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setLayout(null);

        img_lbl.setBackground(new java.awt.Color(255, 204, 51));
        img_lbl.setForeground(new java.awt.Color(153, 255, 153));
        img_lbl.setText("                 PHOTO");
        img_lbl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(img_lbl);
        img_lbl.setBounds(650, 100, 120, 110);

        gvoi.setText("Gestion Des Voitures");
        gvoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gvoiActionPerformed(evt);
            }
        });
        jPanel1.add(gvoi);
        gvoi.setBounds(620, 390, 170, 140);

        gdem.setText("Gestion Des Demandes");
        gdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gdemActionPerformed(evt);
            }
        });
        jPanel1.add(gdem);
        gdem.setBounds(980, 390, 170, 140);

        jButton4.setText("Gestion Des Clients");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(250, 390, 170, 140);

        logout.setText("Deconnecter");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(650, 240, 120, 30);

        conect_user.setFont(new java.awt.Font("Vijaya", 1, 24)); // NOI18N
        conect_user.setText("Admin00");
        jPanel1.add(conect_user);
        conect_user.setBounds(660, 210, 180, 30);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(640, 90, 140, 130);

        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 380, 190, 160);

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(610, 380, 190, 160);

        jLabel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(970, 380, 190, 160);

        jLabel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(650, 240, 120, 30);

        txt_date.setText("File");
        jMenuBar1.add(txt_date);

        txt_time.setText("Edit");
        jMenuBar1.add(txt_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       LogIn l=new LogIn();
       l.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    /* Client c=new Client();
     c.setVisible(true);*/
     //this.dispose();
     
     Client addEmp=new Client();
        //jPAppli.removeAll();
        //jPAppli.repaint();
        //jPAppli.add(addEmp);
        addEmp.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void gvoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gvoiActionPerformed
       Voiture v=new Voiture();
       v.setVisible(true);
       
    }//GEN-LAST:event_gvoiActionPerformed

    private void gdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gdemActionPerformed
        Demande d=new Demande();
        d.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_gdemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel conect_user;
    private javax.swing.JButton gdem;
    private javax.swing.JButton gvoi;
    private javax.swing.JLabel img_lbl;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JMenu txt_date;
    private javax.swing.JMenu txt_time;
    // End of variables declaration//GEN-END:variables
}
