/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View;

import com.DataBase.SingletonConnection;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YouSsef
 */
public class MonApplication extends javax.swing.JFrame {

    /**
     * Creates new form MonApplication
     */
    Connection conn;
    PreparedStatement ps,ps2;
    ResultSet rs,rs2;
    static int idx;
    DefaultTableModel model=new DefaultTableModel();
    public MonApplication() {
        initComponents();
    this.setSize(1090, 680);
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        conn=SingletonConnection.getConnection();
        try {
            ps=conn.prepareStatement("Select * from Villes ");
            ps.executeQuery();
            rs=ps.getResultSet();
            while(rs.next()){
                        villeItem.addItem(rs.getString("name"));
                             }
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        /*
        Remplir le tableau
        */
        model.addColumn("NOM");
        model.addColumn("EMAIL");
        model.addColumn("PASSWORD");
        model.addColumn("TEL");
        model.addColumn("FAX");
        model.addColumn("ADRESSE");
        model.addColumn("VILLE");
        model.addColumn("PAYS");
        
        
        try{
            Statement st2 = conn.createStatement();
            rs2=st2.executeQuery("select * from clients c, villes v ,users u where c.ville_id=v.id_ville and c.user_id=u.id_user");
            while(rs2.next())
            {
                model.addRow(new Object[] {
                    rs2.getString("nom"),
                    rs2.getString("email"),
                    rs2.getString("password"),
                    rs2.getString("tel"),
                    rs2.getString("fax"),
                    rs2.getString("adresse"),
                    rs2.getString("name"),
                    rs2.getString("pays")
                });
            }
        }catch(Exception e)
        {
            System.err.println(e);
        }
        tble.setModel(model);
        
        /*
        Fin remplissage
        */
                ImageIcon ic=new ImageIcon("src\\icon\\add.png");
                Image ii=ic.getImage();
                Image ii2=ii.getScaledInstance(btville.getWidth(), btville.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icc=new ImageIcon(ii2);
         
                    btville.setIcon(icc);
                    
                ImageIcon ab=new ImageIcon("src\\icon\\searchUser.png");
                Image bc=ab.getImage();
                Image cd=bc.getScaledInstance(serchUser.getWidth(), serchUser.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon de=new ImageIcon(cd);
                serchUser.setIcon(de);
                
                ImageIcon a1=new ImageIcon("src\\icon\\addCl.png");
                Image a2=a1.getImage();
                Image a3=a2.getScaledInstance(addcl.getWidth(), addcl.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon a4=new ImageIcon(a3);
                addcl.setIcon(a4);
                
                ImageIcon b1=new ImageIcon("src\\icon\\update.png");
                Image b2=b1.getImage();
                Image b3=b2.getScaledInstance(updatebt.getWidth(), updatebt.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon b4=new ImageIcon(b3);
                updatebt.setIcon(b4);
                
                ImageIcon d1=new ImageIcon("src\\icon\\deletecl.png");
                Image d2=d1.getImage();
                Image d3=d2.getScaledInstance(deletebt.getWidth(), deletebt.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon d4=new ImageIcon(d3);
                deletebt.setIcon(d4);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void afficher()
    {
        
            try{
                
            model.setRowCount(0);
            Statement st2 = conn.createStatement();
            rs2=st2.executeQuery("select * from clients c, villes v ,users u where c.ville_id=v.id_ville and c.user_id=u.id_user");
            while(rs2.next())
            {
                model.addRow(new Object[] {
                    rs2.getString("nom"),
                    rs2.getString("email"),
                    rs2.getString("password"),
                    rs2.getString("tel"),
                    rs2.getString("fax"),
                    rs2.getString("adresse"),
                    rs2.getString("name"),
                    rs2.getString("pays")
                });
            }
        }catch(Exception e)
        {
            System.err.println(e);
        }
        tble.setModel(model);
    }
    private void deplace(int i)
    {
        try{
            mailtxt.setText(model.getValueAt(i,1).toString());
            pwdtxt.setText(model.getValueAt(i,2).toString());
            nomtxt.setText(model.getValueAt(i,0).toString());
            teltxt.setText(model.getValueAt(i,3).toString());
            faxtxt.setText(model.getValueAt(i,4).toString());
            adrtxt.setText(model.getValueAt(i,5).toString());
            villeItem.setSelectedItem(model.getValueAt(i,6).toString());
            paystxt.setText(model.getValueAt(i,7).toString());
        }catch(Exception e)
        {
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "erreur de deplacement"+e.getLocalizedMessage());
        }
    }
    /*
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        paystxt = new javax.swing.JTextField();
        mailtxt = new javax.swing.JTextField();
        pwdtxt = new javax.swing.JTextField();
        nomtxt = new javax.swing.JTextField();
        teltxt = new javax.swing.JTextField();
        faxtxt = new javax.swing.JTextField();
        adrtxt = new javax.swing.JTextField();
        villeItem = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        serchUser = new javax.swing.JButton();
        addcl = new javax.swing.JButton();
        updatebt = new javax.swing.JButton();
        deletebt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tble = new javax.swing.JTable();
        btville = new javax.swing.JButton();
        txtre = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        deletebt1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tble1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        msgaff = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nomvoi = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nomv = new javax.swing.JTextField();
        vil = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        nomcl = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        updatebt1 = new javax.swing.JButton();
        deletebt2 = new javax.swing.JButton();
        addcl1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tble2 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 233));
        jPanel2.setLayout(null);

        jLabel2.setText("Pays                 :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 430, 100, 30);

        jLabel3.setText("Fax                   :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 280, 100, 30);

        jLabel4.setText("Tel                     :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 240, 100, 30);

        jLabel5.setText("Email                   :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 90, 100, 30);

        jLabel7.setText("Password            :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 140, 100, 30);

        jLabel6.setText("Nom & Prénom   :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 190, 100, 30);

        jLabel8.setText("Adresse            :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 330, 100, 30);

        jLabel9.setText("Ville                   :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 380, 100, 30);

        paystxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paystxtActionPerformed(evt);
            }
        });
        jPanel2.add(paystxt);
        paystxt.setBounds(120, 430, 210, 30);
        jPanel2.add(mailtxt);
        mailtxt.setBounds(120, 90, 210, 30);

        pwdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdtxtActionPerformed(evt);
            }
        });
        jPanel2.add(pwdtxt);
        pwdtxt.setBounds(120, 140, 210, 30);

        nomtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomtxtActionPerformed(evt);
            }
        });
        jPanel2.add(nomtxt);
        nomtxt.setBounds(120, 190, 210, 30);

        teltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teltxtActionPerformed(evt);
            }
        });
        jPanel2.add(teltxt);
        teltxt.setBounds(120, 240, 210, 30);

        faxtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faxtxtActionPerformed(evt);
            }
        });
        jPanel2.add(faxtxt);
        faxtxt.setBounds(120, 280, 210, 30);

        adrtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adrtxtActionPerformed(evt);
            }
        });
        jPanel2.add(adrtxt);
        adrtxt.setBounds(120, 330, 210, 30);

        villeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villeItemActionPerformed(evt);
            }
        });
        jPanel2.add(villeItem);
        villeItem.setBounds(120, 380, 200, 30);

        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information Du Client", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 50, 390, 430);

        serchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serchUserActionPerformed(evt);
            }
        });
        jPanel2.add(serchUser);
        serchUser.setBounds(980, 540, 50, 40);

        addcl.setText("Ajouter");
        addcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addclActionPerformed(evt);
            }
        });
        jPanel2.add(addcl);
        addcl.setBounds(50, 490, 70, 50);

        updatebt.setText("Modifier");
        updatebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtActionPerformed(evt);
            }
        });
        jPanel2.add(updatebt);
        updatebt.setBounds(150, 490, 70, 50);

        deletebt.setText("Supprimer");
        deletebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtActionPerformed(evt);
            }
        });
        jPanel2.add(deletebt);
        deletebt.setBounds(250, 490, 70, 50);

        tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        tble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tble);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(430, 70, 630, 402);

        btville.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btvilleActionPerformed(evt);
            }
        });
        jPanel2.add(btville);
        btville.setBounds(330, 380, 50, 30);

        txtre.setText("jTextField1");
        jPanel2.add(txtre);
        txtre.setBounds(760, 550, 210, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(760, 510, 130, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel10.setText("Rechercher par:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(660, 520, 90, 20);

        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rechercher", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(540, 490, 520, 100);

        jLabel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listes Des Clients", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(420, 50, 650, 440);

        jTabbedPane1.addTab("Gestion des clients", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 233));
        jPanel3.setLayout(null);

        deletebt1.setText("Supprimer");
        deletebt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebt1ActionPerformed(evt);
            }
        });
        jPanel3.add(deletebt1);
        deletebt1.setBounds(50, 30, 90, 60);

        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 20, 1050, 80);

        tble1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        tble1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tble1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tble1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(450, 130, 610, 290);

        jLabel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("La Listes Des Voitures"), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel14);
        jLabel14.setBounds(440, 110, 630, 320);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(720, 250, 262, 120);

        msgaff.setColumns(20);
        msgaff.setRows(5);
        jScrollPane4.setViewportView(msgaff);

        jPanel3.add(jScrollPane4);
        jScrollPane4.setBounds(160, 450, 240, 140);

        jLabel15.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel15.setText("MESSAGE       :");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(30, 450, 140, 30);

        jLabel16.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel16.setText("Voiture           :");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(30, 200, 120, 14);
        jPanel3.add(nomvoi);
        nomvoi.setBounds(160, 190, 230, 27);

        jLabel17.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel17.setText("Télephone       :");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(30, 330, 140, 14);
        jPanel3.add(mail);
        mail.setBounds(160, 400, 230, 27);

        jLabel18.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel18.setText("Vendeur          :");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(30, 160, 140, 14);

        jLabel19.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel19.setText("Ville               :");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(30, 370, 140, 14);

        jLabel20.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel20.setText("Email             :");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(30, 410, 140, 14);

        jLabel21.setFont(new java.awt.Font("URW Bookman L", 1, 14)); // NOI18N
        jLabel21.setText("Nom du Clients:");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(30, 290, 140, 14);
        jPanel3.add(nomv);
        nomv.setBounds(160, 150, 230, 27);
        jPanel3.add(vil);
        vil.setBounds(160, 360, 230, 27);
        jPanel3.add(tel);
        tel.setBounds(160, 320, 230, 27);
        jPanel3.add(nomcl);
        nomcl.setBounds(160, 280, 230, 27);

        jLabel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMATIONS SUR L'OFFRE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 0, 14))); // NOI18N
        jPanel3.add(jLabel22);
        jLabel22.setBounds(20, 120, 390, 110);

        jLabel23.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMATIONS SUR LE CLIENT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Serif", 0, 14))); // NOI18N
        jPanel3.add(jLabel23);
        jLabel23.setBounds(20, 260, 400, 340);

        jTabbedPane1.addTab("Gestion des Demandes", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 233));
        jPanel4.setLayout(null);

        updatebt1.setText("Update");
        jPanel4.add(updatebt1);
        updatebt1.setBounds(180, 30, 90, 60);

        deletebt2.setText("Supprimer");
        deletebt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebt2ActionPerformed(evt);
            }
        });
        jPanel4.add(deletebt2);
        deletebt2.setBounds(310, 30, 90, 60);

        addcl1.setText("Ajouter");
        addcl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcl1ActionPerformed(evt);
            }
        });
        jPanel4.add(addcl1);
        addcl1.setBounds(60, 30, 90, 60);

        tble2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13", "Title 14", "Title 15", "Title 16"
            }
        ));
        jScrollPane5.setViewportView(tble2);

        jPanel4.add(jScrollPane5);
        jScrollPane5.setBounds(40, 130, 1020, 340);

        jLabel24.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("La Listes Des Voitures"), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        jPanel4.add(jLabel24);
        jLabel24.setBounds(20, 110, 1050, 370);

        jLabel25.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.add(jLabel25);
        jLabel25.setBounds(20, 20, 1050, 80);

        jTabbedPane1.addTab("Gestion des Voitures", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btvilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btvilleActionPerformed
        addVille a=new addVille();
        a.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btvilleActionPerformed

    private void tbleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbleMouseClicked
        try
        {
            int i=tble.getSelectedRow();
            deplace(i);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "erruer de delacement "+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tbleMouseClicked

    private void deletebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtActionPerformed

        String mail=mailtxt.getText();
        String nom=nomtxt.getText();
        if(JOptionPane.showConfirmDialog(null, "wach bessa7 baghi tmsa7 "+nom,"modification",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {int id_usr = 0;
            try {
                PreparedStatement s1=conn.prepareStatement("select * from users where email=?");
                s1.setString(1, mail);
                s1.executeQuery();
                ResultSet r=s1.getResultSet();
                r.next();
                id_usr=r.getInt("id_user");
                r.close();
                s1.close();
            } catch (SQLException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                PreparedStatement oo=conn.prepareStatement("delete from clients where user_id=?");
                oo.setInt(1, id_usr);
                oo.executeUpdate();
                oo.close();
                PreparedStatement o=conn.prepareStatement("delete from users where id_user=?");
                o.setInt(1, id_usr);
                o.executeUpdate();
                o.close();
                afficher();
                mailtxt.setText("");pwdtxt.setText("");nomtxt.setText("");
                paystxt.setText("");teltxt.setText("");faxtxt.setText("");adrtxt.setText("");villeItem.setSelectedItem(3);
            } catch (SQLException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deletebtActionPerformed

    private void updatebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtActionPerformed

        String mail=mailtxt.getText();
        String pwd=pwdtxt.getText();
        String nom=nomtxt.getText();
        int tel=Integer.parseInt(teltxt.getText());
        int fax=Integer.parseInt(faxtxt.getText());
        String adr=adrtxt.getText();
        String pays=paystxt.getText();
        String vill=villeItem.getSelectedItem().toString();

        int id_usr = 0;
        try {
            PreparedStatement s1=conn.prepareStatement("select * from users where email=?");
            s1.setString(1, mail);
            s1.executeQuery();
            ResultSet r=s1.getResultSet();
            r.next();
            id_usr=r.getInt("id_user");
            r.close();
            s1.close();
        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* if(JOptionPane.showConfirmDialog(null, "wach bessa7","modification",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            try {
                PreparedStatement po=conn.prepareStatement("");
                st.executeUpdate("Update etudiant set Nom='"+txtno.getText()+"',prenom='"+txtpr.getText()+"',branche='"+txtbr.getSelectedItem().toString()+"',note='"+txtnot.getText()+
                    "' where id="+txtid.getText());
                afficher();
                JOptionPane.showMessageDialog(null, "bien modifier");

            } catch (SQLException ex) {
                Logger.getLogger(Gestion_des_notes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }*/
    }//GEN-LAST:event_updatebtActionPerformed

    private void addclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addclActionPerformed
        //insert into users() values(mail,passwd,client,CURRENT_DATE(),CURRENT_DATE());
        boolean ext=false;
        String mail=mailtxt.getText();
        String pwd=pwdtxt.getText();
        String sql="insert into users(email,password,created,modified) values (?,?,CURRENT_DATE(),CURRENT_DATE())";
        try {
            PreparedStatement s2=conn.prepareStatement("select * from users where email=?");
            s2.setString(1, mail);
            s2.executeQuery();
            ResultSet r=s2.getResultSet();
            if(r.next())
            {
                ext=true;
                JOptionPane.showMessageDialog(null, " user deja exist");
            }else
            {
                PreparedStatement pss=conn.prepareStatement(sql);
                pss.setString(1, mail);
                pss.setString(2, pwd);
                pss.executeUpdate();
                System.out.println("users inscrit");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
        //insert into clients(nom,tel,ville_id,user_id,fax,adresse,pays)
        String nom=nomtxt.getText();
        int tel=Integer.parseInt(teltxt.getText());
        int fax=Integer.parseInt(faxtxt.getText());
        String adr=adrtxt.getText();
        String pays=paystxt.getText();
        String vill=villeItem.getSelectedItem().toString();
        //mail
        int id_usr = 0;
        if(ext==false){
            try {
                PreparedStatement s1=conn.prepareStatement("select * from users where email=?");
                s1.setString(1, mail);
                s1.executeQuery();
                ResultSet r=s1.getResultSet();
                r.next();
                id_usr=r.getInt("id_user");
                r.close();
                s1.close();
            } catch (SQLException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }

            //ville
            int id_ville=1;
            try {
                PreparedStatement ww=conn.prepareStatement("select * from villes where name=?");
                ww.setString(1, vill);
                ww.executeQuery();
                ResultSet rt=ww.getResultSet();
                rt.next();
                id_ville= rt.getInt("id_ville");
                rt.close();
                ww.close();
            } catch (SQLException ex) {
                Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
            }
            //nom,tel,fax,adr,pays,id_usr,id_ville
            String sql2="insert into clients(nom,tel,ville_id,user_id,fax,adresse,pays)"
            + "values (?,?,?,?,?,?,?)";
            if(id_usr!=0){
                try {
                    PreparedStatement pp=conn.prepareStatement(sql2);
                    pp.setString(1, nom);
                    pp.setInt(2, tel);
                    pp.setInt(3, id_ville);
                    pp.setInt(4, id_usr);
                    pp.setInt(5, fax);
                    pp.setString(6, adr);
                    pp.setString(7, pays);
                    pp.executeUpdate();
                    System.out.println("client bien ajoutee");
                    JOptionPane.showMessageDialog(null, " Client Bien ajouté ");
                    afficher();
                    mailtxt.setText("");pwdtxt.setText("");nomtxt.setText("");
                    paystxt.setText("");teltxt.setText("");faxtxt.setText("");adrtxt.setText("");villeItem.setSelectedItem(3);

                } catch (SQLException ee) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ee);
                }

            }
        }
    }//GEN-LAST:event_addclActionPerformed

    private void serchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serchUserActionPerformed
        try
        {
            model.setRowCount(0);//pour vider la listes des Clients
            PreparedStatement v=conn.prepareStatement("select * from clients c, villes v ,users u where c.ville_id=v.id_ville and c.user_id=u.id_user and c.nom like '%?%'");
            v.setString(1, txtre.getText());
            v.executeQuery();
            ResultSet rr=v.getResultSet();
            while(rr.next())
            {
                Object [] cl={rs2.getString("nom"),
                    rr.getString("email"),
                    rr.getString("password"),
                    rr.getString("tel"),
                    rr.getString("fax"),
                    rr.getString("adresse"),
                    rr.getString("name"),
                    rr.getString("pays")};
                model.addRow(cl);
            }
            if(model.getRowCount()==0)
            JOptionPane.showMessageDialog(null, "makyn hta chi wahed bhad smiya");
            else {
                int  i=0;
                deplace(i);
            }
        }catch(Exception e)
        {
            System.out.println("loooooooooooooo");
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_serchUserActionPerformed

    private void villeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villeItemActionPerformed

    }//GEN-LAST:event_villeItemActionPerformed

    private void adrtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adrtxtActionPerformed

    private void faxtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faxtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faxtxtActionPerformed

    private void teltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teltxtActionPerformed

    private void nomtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomtxtActionPerformed

    private void pwdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdtxtActionPerformed

    private void paystxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paystxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paystxtActionPerformed

    private void deletebt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebt1ActionPerformed
        try {
            if(JOptionPane.showConfirmDialog(null,"est ce que tu veut vraiment supprimer cette demande!","Suppression", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            {
                PreparedStatement pps=conn.prepareStatement("delete from demandes where id_demande=?");
                pps.setInt(1, idx);
                pps.executeUpdate();
                pps.close();
                afficher();

            }

        } catch (SQLException ex) {
            Logger.getLogger(Demande.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletebt1ActionPerformed

    private void tble1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tble1MouseClicked
        try
        {
            int i=tble.getSelectedRow();
            deplace(i);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "erruer de delacement "+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tble1MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void deletebt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deletebt2ActionPerformed

    private void addcl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcl1ActionPerformed
        voitR r=new voitR();
        r.setVisible(true);
    }//GEN-LAST:event_addcl1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcl;
    private javax.swing.JButton addcl1;
    private javax.swing.JTextField adrtxt;
    private javax.swing.JButton btville;
    private javax.swing.JButton deletebt;
    private javax.swing.JButton deletebt1;
    private javax.swing.JButton deletebt2;
    private javax.swing.JTextField faxtxt;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField mailtxt;
    private javax.swing.JTextArea msgaff;
    private javax.swing.JTextField nomcl;
    private javax.swing.JTextField nomtxt;
    private javax.swing.JTextField nomv;
    private javax.swing.JTextField nomvoi;
    private javax.swing.JTextField paystxt;
    private javax.swing.JTextField pwdtxt;
    private javax.swing.JButton serchUser;
    private javax.swing.JTable tble;
    private javax.swing.JTable tble1;
    private javax.swing.JTable tble2;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField teltxt;
    private javax.swing.JTextField txtre;
    private javax.swing.JButton updatebt;
    private javax.swing.JButton updatebt1;
    private javax.swing.JTextField vil;
    private javax.swing.JComboBox<String> villeItem;
    // End of variables declaration//GEN-END:variables
}
