/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.View;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author YouSsef
 */
public class registr_voiture extends javax.swing.JFrame {

    /**
     * Creates new form registr_voiture
     */
    public registr_voiture() {
        initComponents();
        this.setTitle("Enregestrer un Voiture");
       // C:\Users\YouSsef\Desktop\nn.jpg
       System.out.println("ee");
       ImageIcon ic=new ImageIcon("src\\icon\\nn.jpg");
                Image ii=ic.getImage();
                Image ii2=ii.getScaledInstance(label_bg.getWidth(), label_bg.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icc=new ImageIcon(ii2);
                /*
                irst way: Image img = myIcon2.getImage(); Image newimg = img.getScaledInstance(230, 310, java.awt.Image.SCALE_SMOOTH);
 newIcon = new ImageIcon(newimg);
                */
                    label_bg.setIcon(icc);
    }
    
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        System.out.println("ee");
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_photo_voiture.getWidth(), lbl_photo_voiture.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
      
          ActionListener a=  new ActionListener() {

        public void actionPerformed(ActionEvent e) {
        
            JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.home")));
          //filter the files
            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              String path = selectedFile.getAbsolutePath();
              
              lbl_photo_voiture.setIcon(ResizeImage(path));
              path_txt.setText(path);
          }
           //if the user click on save in Jfilechooser


          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Select");
          }
        }
          }
      ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        kilo_txt = new javax.swing.JTextField();
        annee_txt = new javax.swing.JTextField();
        Etat_item = new javax.swing.JComboBox<>();
        marque_item = new javax.swing.JComboBox<>();
        titre_txt = new javax.swing.JTextField();
        prix_txt = new javax.swing.JTextField();
        modele_item = new javax.swing.JComboBox<>();
        ville_item = new javax.swing.JComboBox<>();
        carburant_item = new javax.swing.JComboBox<>();
        couleur_item = new javax.swing.JComboBox<>();
        BV_item = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc_area = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        option_item = new javax.swing.JList<>();
        lbl_photo_voiture = new javax.swing.JLabel();
        path_txt = new javax.swing.JTextField();
        browse = new javax.swing.JButton();
        annu_bot = new javax.swing.JButton();
        save_bot = new javax.swing.JButton();
        label_bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Modèle          :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 120, 100, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Description   :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 380, 100, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Kilométrage  :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 170, 100, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Ville             :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 230, 100, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Couleur        :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 280, 100, 20);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Etat              :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 330, 100, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Marque           :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 60, 100, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Option         :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(510, 330, 100, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setText("Année            :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(510, 170, 100, 20);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("Carburant     :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(510, 230, 100, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("Boite à Vitesse     :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(480, 280, 120, 20);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 0));
        jLabel16.setText("Prix                :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(510, 120, 100, 20);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setText("Titre              :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(20, 60, 100, 20);

        kilo_txt.setBorder(null);
        kilo_txt.setMargin(new java.awt.Insets(7, 7, 7, 7));
        kilo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilo_txtActionPerformed(evt);
            }
        });
        jPanel1.add(kilo_txt);
        kilo_txt.setBounds(120, 170, 330, 30);

        annee_txt.setBorder(null);
        annee_txt.setMargin(new java.awt.Insets(7, 7, 7, 7));
        annee_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annee_txtActionPerformed(evt);
            }
        });
        jPanel1.add(annee_txt);
        annee_txt.setBounds(610, 170, 330, 30);

        Etat_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Etat_item);
        Etat_item.setBounds(120, 330, 150, 30);

        marque_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(marque_item);
        marque_item.setBounds(610, 60, 150, 30);

        titre_txt.setBorder(null);
        titre_txt.setMargin(new java.awt.Insets(7, 7, 7, 7));
        titre_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titre_txtActionPerformed(evt);
            }
        });
        jPanel1.add(titre_txt);
        titre_txt.setBounds(120, 60, 330, 30);

        prix_txt.setBorder(null);
        prix_txt.setMargin(new java.awt.Insets(7, 7, 7, 7));
        prix_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prix_txtActionPerformed(evt);
            }
        });
        jPanel1.add(prix_txt);
        prix_txt.setBounds(610, 120, 330, 30);

        modele_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(modele_item);
        modele_item.setBounds(120, 120, 150, 30);

        ville_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ville_item);
        ville_item.setBounds(120, 220, 150, 30);

        carburant_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(carburant_item);
        carburant_item.setBounds(610, 220, 150, 30);

        couleur_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(couleur_item);
        couleur_item.setBounds(120, 280, 150, 30);

        BV_item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(BV_item);
        BV_item.setBounds(610, 280, 150, 30);

        desc_area.setColumns(20);
        desc_area.setRows(5);
        jScrollPane1.setViewportView(desc_area);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 380, 340, 96);

        option_item.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(option_item);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(610, 330, 180, 60);

        lbl_photo_voiture.setText("         Photo Voiture");
        lbl_photo_voiture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lbl_photo_voiture);
        lbl_photo_voiture.setBounds(1010, 40, 220, 160);
        jPanel1.add(path_txt);
        path_txt.setBounds(1080, 210, 170, 30);

        browse.setText("Browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });
        jPanel1.add(browse);
        browse.setBounds(990, 210, 90, 30);

        annu_bot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        annu_bot.setText("Annuler");
        jPanel1.add(annu_bot);
        annu_bot.setBounds(1110, 390, 130, 40);

        save_bot.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save_bot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/information/system/images/Save-icon.png"))); // NOI18N
        save_bot.setText("Enregistrer");
        jPanel1.add(save_bot);
        save_bot.setBounds(970, 390, 130, 40);

        label_bg.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(label_bg);
        label_bg.setBounds(0, 0, 1260, 40);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1261, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kilo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kilo_txtActionPerformed

    private void annee_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annee_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annee_txtActionPerformed

    private void titre_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titre_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titre_txtActionPerformed

    private void prix_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prix_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prix_txtActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
                browse.addActionListener(a);      // TODO add your handling code here:
    }//GEN-LAST:event_browseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registr_voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registr_voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registr_voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registr_voiture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registr_voiture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BV_item;
    private javax.swing.JComboBox<String> Etat_item;
    private javax.swing.JTextField annee_txt;
    private javax.swing.JButton annu_bot;
    private javax.swing.JButton browse;
    private javax.swing.JComboBox<String> carburant_item;
    private javax.swing.JComboBox<String> couleur_item;
    private javax.swing.JTextArea desc_area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kilo_txt;
    private javax.swing.JLabel label_bg;
    private javax.swing.JLabel lbl_photo_voiture;
    private javax.swing.JComboBox<String> marque_item;
    private javax.swing.JComboBox<String> modele_item;
    private javax.swing.JList<String> option_item;
    private javax.swing.JTextField path_txt;
    private javax.swing.JTextField prix_txt;
    private javax.swing.JButton save_bot;
    private javax.swing.JTextField titre_txt;
    private javax.swing.JComboBox<String> ville_item;
    // End of variables declaration//GEN-END:variables
}
